package platform

XCB_CW_BACK_PIXMAP :: 0
XCB_CW_BACK_PIXEL :: 1
XCB_CW_BORDER_PIXMAP :: 2
XCB_CW_BORDER_PIXEL :: 3
XCB_CW_BIT_GRAVITY :: 4
XCB_CW_WIN_GRAVITY :: 5
XCB_CW_BACKING_STORE :: 6
XCB_CW_BACKING_PLANES :: 7
XCB_CW_BACKING_PIXEL :: 8
XCB_CW_OVERRIDE_REDIRECT :: 9
XCB_CW_SAVE_UNDER :: 10
XCB_CW_EVENT_MASK :: 11
XCB_CW_DONT_PROPAGATE :: 12
XCB_CW_COLORMAP :: 13
XCB_CW_CURSOR :: 14
XCB_PROP_MODE_REPLACE :: 0
XCB_ATOM_WM_NAME :: 39
XCB_ATOM_STRING :: 31
